"""Tailor worker — rewrites resume bullets and cover letter (BUILD.md Task 1.3, arch.F.4)."""

from __future__ import annotations

import subprocess
import textwrap
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger(__name__)

_PROMPT_PATH = Path(__file__).resolve().parents[1] / "prompts" / "tailor.md"
_CV_DIR = Path(__file__).resolve().parents[2] / "cv"
_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output"


def _load_cv(track: str) -> str:
    path = _CV_DIR / f"{track.lower()}.md"
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _generate_pdf(md_path: Path, pdf_path: Path) -> bool:
    """Call generate-pdf.mjs via Node subprocess. Returns True on success."""
    script = Path(__file__).resolve().parents[2] / "generate-pdf.mjs"
    if not script.exists():
        log.warning("generate_pdf_script_missing", path=str(script))
        return False
    proc = subprocess.run(
        ["node", str(script), "--input", str(md_path), "--output", str(pdf_path)],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if proc.returncode != 0:
        log.error("generate_pdf_failed", stderr=proc.stderr[:500])
        return False
    return True


def _diff_summary(original: str, tailored: str) -> str:
    """Return a short bullet-diff of changed lines."""
    orig_lines = set(original.splitlines())
    new_lines = set(tailored.splitlines())
    added = [f"+ {line}" for line in (new_lines - orig_lines) if line.strip().startswith("-")]
    removed = [f"- {line}" for line in (orig_lines - new_lines) if line.strip().startswith("-")]
    changes = removed[:4] + added[:4]
    return "\n".join(changes) if changes else "No bullet changes detected."


def tailor_resume(
    jd_text: str,
    track: str | None,
    run_id: str,
    *,
    anthropic_client: Any | None = None,
    keywords: list[str] | None = None,
) -> dict[str, str]:
    """
    Produce a tailored PDF and cover letter for the given JD.

    Returns ``{pdf_path, cover_path, diff_summary}``.
    """
    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    track = (track or "MLE").upper()
    if track not in {"DA", "MLE", "DE"}:
        track = "MLE"

    cv_text = _load_cv(track)
    system = _PROMPT_PATH.read_text(encoding="utf-8")

    # Build tailored markdown with simple bullet enhancement when no LLM available
    if anthropic_client is None:
        from agents.tools.keychain import claude_api_key

        key = claude_api_key()
        if key:
            from langchain_anthropic import ChatAnthropic
            from langchain_core.messages import HumanMessage, SystemMessage

            llm = ChatAnthropic(model="claude-sonnet-4-5", api_key=key, max_tokens=2048)
            kw_str = ", ".join(keywords or [])
            user_msg = (
                f"JD TEXT:\n{jd_text[:2000]}\n\n"
                f"TRACK: {track}\n"
                f"TARGET KEYWORDS: {kw_str}\n\n"
                f"MASTER CV:\n{cv_text[:2000]}\n\n"
                "Produce: 1) tailored CV markdown, 2) 150-220 word cover letter, 3) diff summary."
            )
            resp = llm.invoke([SystemMessage(content=system), HumanMessage(content=user_msg)])
            raw = resp.content if hasattr(resp, "content") else str(resp)
        else:
            log.warning("tailor_no_api_key_using_pass_through")
            raw = cv_text  # pass-through in dry-run / CI

    # Write tailored markdown
    md_path = _OUTPUT_DIR / f"{run_id}-tailored.md"
    md_path.write_text(cv_text if anthropic_client is None else raw, encoding="utf-8")

    # Attempt PDF generation via Node script
    pdf_path = _OUTPUT_DIR / f"{run_id}.pdf"
    _generate_pdf(md_path, pdf_path)

    # Write cover letter stub
    cover_path = _OUTPUT_DIR / f"{run_id}-cover.md"
    cover_text = textwrap.dedent(f"""\
        # Cover Letter — {run_id} ({track})

        Dear Hiring Manager,

        I am excited to apply for this {track} role. [Cover letter generated by Tailor agent.]

        Best regards,
        {_load_profile_name()}
    """)
    cover_path.write_text(cover_text, encoding="utf-8")

    return {
        "pdf_path": str(pdf_path),
        "cover_path": str(cover_path),
        "diff_summary": _diff_summary(cv_text, md_path.read_text(encoding="utf-8")),
    }


def _load_profile_name() -> str:
    try:
        import yaml  # type: ignore[import-untyped]

        cfg_path = Path(__file__).resolve().parents[2] / "config" / "profile.yml"
        if cfg_path.exists():
            cfg = yaml.safe_load(cfg_path.read_text())
            return cfg.get("identity", {}).get("display_name", "")
    except Exception:
        pass
    return ""
